services:
  - type: web
    name: moodle
    env: docker
    plan: free
    branch: main
    autoDeploy: false
    dockerfilePath: Dockerfile
    envVars:
      - key: MOODLE_DATABASE_TYPE
        value: pgsql
      - key: MOODLE_DATABASE_HOST
        fromDatabase:
          name: moodle-db
          property: host
      - key: MOODLE_DATABASE_PORT_NUMBER
        value: 5432
      - key: MOODLE_DATABASE_NAME
        value: moodle
      - key: MOODLE_DATABASE_USER
        value: moodle_user
      - key: MOODLE_DATABASE_PASSWORD
        fromDatabase:
          name: moodle-db
          property: password
      - key: MOODLE_USERNAME
        value: admin
      - key: MOODLE_PASSWORD
        value: admin123
      - key: MOODLE_EMAIL
        value: admin@example.com

databases:
  - name: moodle-db
    plan: free
    databaseName: moodle
    user: moodle_user
